services:
  # UI
  seaspray-ui:
    image: bus-tracker:latest
    ports:
      - "8080:8080"
    environment:
      - BUS_DATA_HOST=data.bus-data.dft.gov.uk
      - BUS_DATA_API_KEY=
      - BUS_OPERATOR_REF=THTR
      - BUSES_TO_TRACK_LIST=X34,X35,X2,X32